version: '3'

volumes:
  postgresdata:

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgresdata:/data/postgres'
